### ISSUE TITLE
add `cmd` flag to networks

### ISSUE THREAD

**Issue by PatrickAlphaC** [Cyfrin/moccasin#121]
In `moccasin.toml`

```toml
[networks.anvil]
is_zksync = false
save_to_db = false

[networks.anvil.cmd]
command = "anvil"
host = "http://127.0.0.1"
post = 8545
args = etc...

```
