### ISSUE TITLE
Network explorer settings are ignored when using `manifest_named`

### ISSUE THREAD

**Issue by benber86** [Cyfrin/moccasin#194]
If I set up a network configuration in moccasin.toml that specifies an etherscan explorer:

```
[networks.polygon-fork]
url = "https://polygon.llamarpc.com"
explorer_uri = "https://api.polygonscan.com/api/"
explorer_type = "etherscan"
explorer_api_key="${POLYGONSCAN_TOKEN}"
chain_id = 137
fork = true
```

and a named contract, specifying that the abi must be retrieved from the explorer
```
[networks.polygon-fork.contracts.quickswap_factory]
address = "0x5757371414417b8C6CAad45bAeF941aBc7d3Ab32"
abi_from_explorer = true
```

When I then try to retrieve the contract using `manifest_named`:

`factory = get_config().get_active_network().manifest_named("quickswap_factory")`

The settings above will be ignored and moccasin will try to fetch `EXPLORER_API_KEY` from the environment variables. 
This is because `manifest_named` does not pass on the named contract's network's information to `boa_get_abi_from_explorer` which in turns reverts to default values.

**Comment by s3bc40** [comment]
Hum, ok it might be an issue then, but I'll let @PatrickAlphaC confirm. And I already see your PR with the solution, that's a good addition!

---

Though I did not encounter this during the Mox trading course where I download the ABIs through:

```sh
mox explorer fetch 0x912CE59144191C1204E64559FE8253a0e49E6548 --network arb-forked --save --name arb
```

With this `moccasin.toml`:

```toml
[project]
src = "src"
out = "out"
dot_env = ".env"
save_abi_path = "abis"

[networks.contracts]
arb = { abi = "abis/arb.json" }

[networks.arb-forked]
fork = true
url = "$ARBITRUM_RPC_URL"
default_account_name = "<AN_ACCOUNT>"
unsafe_password_file = "<A_PATH>"
explorer_uri = 'https://api.arbiscan.io/api'
explorer_type = 'etherscan'
explorer_api_key = "<YOUR_ARB_API_KEY>"
chain_id = 42161
```

But it might not be related and out of context. I'll let the experts review and accept 😄
