### ISSUE TITLE
When running `mox install` with both a moccasin.toml and a pyproject.toml, the moccasin.toml is filled with the pyproject stuff

### ISSUE THREAD

**Issue by PatrickAlphaC** [Cyfrin/moccasin#213]

**Comment by s3bc40** [comment]
Yeah it seems It's adding the following:
```toml
name = "complex-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11, <3.13"

[...]

[tool.moccasin.project]
src = "src"
dependencies = ["moccasin==0.3.0"]

[tool.moccasin.networks.contracts.pyproject_contract]
abi = "BuyMeACoffee"
force_deploy = false

[tool.moccasin.networks.silly_network]
chain_id = 7777
```

Which is the exact content of  `pyproject.toml`

```toml
[project]
name = "complex-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11, <3.13"
dependencies = [
]

[tool.moccasin.project]
src = "src"
dependencies = [
    "moccasin==0.3.0",
]

[tool.moccasin.networks.contracts.pyproject_contract]
abi = "BuyMeACoffee"
force_deploy = false

[tool.moccasin.networks.silly_network]
chain_id = 7777
```
